// Code generated by command: go run asmgen.go -vec -out ../../math/vec/asm_vec_amd64.s -stubs ../../math/vec/asm_vec_stub_amd64.go -pkg=vec. DO NOT EDIT.

//go:build amd64 && !purego

package vec

//go:noescape
func addAssignUint32AVX2(v0 []uint32, v1 []uint32, vOut []uint32)

//go:noescape
func addAssignUint64AVX2(v0 []uint64, v1 []uint64, vOut []uint64)

//go:noescape
func subAssignUint32AVX2(v0 []uint32, v1 []uint32, vOut []uint32)

//go:noescape
func subAssignUint64AVX2(v0 []uint64, v1 []uint64, vOut []uint64)

//go:noescape
func scalarMulAssignUint32AVX2(v0 []uint32, c uint32, vOut []uint32)

//go:noescape
func scalarMulAssignUint64AVX2(v0 []uint64, c uint64, vOut []uint64)

//go:noescape
func scalarMulAddAssignUint32AVX2(v0 []uint32, c uint32, vOut []uint32)

//go:noescape
func scalarMulAddAssignUint64AVX2(v0 []uint64, c uint64, vOut []uint64)

//go:noescape
func scalarMulSubAssignUint32AVX2(v0 []uint32, c uint32, vOut []uint32)

//go:noescape
func scalarMulSubAssignUint64AVX2(v0 []uint64, c uint64, vOut []uint64)

//go:noescape
func elementWiseMulAssignUint32AVX2(v0 []uint32, v1 []uint32, vOut []uint32)

//go:noescape
func elementWiseMulAssignUint64AVX2(v0 []uint64, v1 []uint64, vOut []uint64)

//go:noescape
func elementWiseMulAddAssignUint32AVX2(v0 []uint32, v1 []uint32, vOut []uint32)

//go:noescape
func elementWiseMulAddAssignUint64AVX2(v0 []uint64, v1 []uint64, vOut []uint64)

//go:noescape
func elementWiseMulSubAssignUint32AVX2(v0 []uint32, v1 []uint32, vOut []uint32)

//go:noescape
func elementWiseMulSubAssignUint64AVX2(v0 []uint64, v1 []uint64, vOut []uint64)
