// Code generated by command: go run asmgen.go -fft -out ../../math/poly/asm_fft_amd64.s -stubs ../../math/poly/asm_fft_stub_amd64.go -pkg=poly. DO NOT EDIT.

//go:build amd64 && !purego

package poly

//go:noescape
func fftInPlaceAVX2(coeffs []float64, tw []complex128)

//go:noescape
func ifftInPlaceAVX2(coeffs []float64, twInv []complex128, scale float64)
