// Code generated by command: go run asmgen.go -convert -out ../../math/poly/asm_convert_amd64.s -stubs ../../math/poly/asm_convert_stub_amd64.go -pkg=poly. DO NOT EDIT.

//go:build amd64 && !purego

package poly

//go:noescape
func convertPolyToFourierPolyAssignUint32AVX2(p []uint32, fpOut []float64)

//go:noescape
func convertPolyToFourierPolyAssignUint64AVX2(p []uint64, fpOut []float64)

//go:noescape
func floatModQInPlaceAVX2(coeffs []float64, Q float64, QInv float64)

//go:noescape
func convertFourierPolyToPolyAssignUint32AVX2(fp []float64, pOut []uint32)

//go:noescape
func convertFourierPolyToPolyAssignUint64AVX2(fp []float64, pOut []uint64)

//go:noescape
func convertFourierPolyToPolyAddAssignUint32AVX2(fp []float64, pOut []uint32)

//go:noescape
func convertFourierPolyToPolyAddAssignUint64AVX2(fp []float64, pOut []uint64)

//go:noescape
func convertFourierPolyToPolySubAssignUint32AVX2(fp []float64, pOut []uint32)

//go:noescape
func convertFourierPolyToPolySubAssignUint64AVX2(fp []float64, pOut []uint64)
