// Code generated by command: go run asmgen.go -vec_cmplx -out ../../math/poly/asm_vec_cmplx_amd64.s -stubs ../../math/poly/asm_vec_cmplx_stub_amd64.go -pkg=poly. DO NOT EDIT.

//go:build amd64 && !purego

package poly

//go:noescape
func addCmplxAssignAVX2(v0 []float64, v1 []float64, vOut []float64)

//go:noescape
func subCmplxAssignAVX2(v0 []float64, v1 []float64, vOut []float64)

//go:noescape
func negCmplxAssignAVX2(v0 []float64, vOut []float64)

//go:noescape
func floatMulCmplxAssignAVX2(v0 []float64, c float64, vOut []float64)

//go:noescape
func floatMulAddCmplxAssignAVX2(v0 []float64, c float64, vOut []float64)

//go:noescape
func floatMulSubCmplxAssignAVX2(v0 []float64, c float64, vOut []float64)

//go:noescape
func cmplxMulCmplxAssignAVX2(v0 []float64, c complex128, vOut []float64)

//go:noescape
func cmplxMulAddCmplxAssignAVX2(v0 []float64, c complex128, vOut []float64)

//go:noescape
func cmplxMulSubCmplxAssignAVX2(v0 []float64, c complex128, vOut []float64)

//go:noescape
func elementWiseMulCmplxAssignAVX2(v0 []float64, v1 []float64, vOut []float64)

//go:noescape
func elementWiseMulAddCmplxAssignAVX2(v0 []float64, v1 []float64, vOut []float64)

//go:noescape
func elementWiseMulSubCmplxAssignAVX2(v0 []float64, v1 []float64, vOut []float64)
